version: '3'

services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=n8n.yourdomain.com
      - N8N_PORT=5678
      - VUE_APP_URL_BASE_API=http://localhost:5678/
    volumes:
      - ~/.n8n:/home/node/.n8n
